version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: yarn start
    volumes:
      - .:/home/node
      - node_modules:/home/node/node_modules
    depends_on:
      - db

  db:
    image: postgis/postgis:12-2.5-alpine
    volumes:
      - ./db-init.sh:/docker-entrypoint-initdb.d/init.sh
      - pg-data:/var/lib/postgresql/data
    expose:
      - "5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  node_modules:
  pg-data:
